import { ClasseEquipamento, PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

/**
 * Fórmulas de quantidade avaliadas via mathjs no ConfiguradorService.
 *
 * Variáveis disponíveis no contexto:
 *
 * PORTÕES PEDESTRE:  ped_piv_manual, ped_piv_auto, ped_desl_piso, ped_desl_teto, ped_piv_vidro, ped_outro
 * CONTROLE PED:      eclusa_pedestre, leitor_tag_ped, biometria_digital, biometria_facial, opcao_saida_ped (0=Interfone,1=Botão)
 * CÂMERAS/INTERFONE: interfone_aut, cam_aut, interfone_rem, cam_rem, integracao_interfone (0|1), cam_elev
 * TUBULAÇÃO (calc):  tub_aut, tub_rem, tub_vei
 * PORTÕES VEI:       desl_p, desl_m, desl_g, basc_simples, piv_simples, piv_duplo, vei_outro
 * MOTORES VEI:       motor_desl_p, motor_desl_m, motor_desl_g, motor_basc, motor_piv_simples, motor_piv_duplo, motor_outro
 * CONTROLE VEI:      controle_remoto (0|1), antenas_tag_vei, biometria_facial_vei, eclusa_veiculo, intertrav_ped, refletores
 * PERÍMETRO:         metros_cerca, sensores_barreira, cerca_tipo (0=Nenhuma,1=Completa,2=Apenas fiação)
 * DISPOSITIVOS:      tag_pedestre, pulseira_ped, controle_veiculos, tag_vei_comum, tag_vei_blindada
 * LIXEIRA:           lixeira_modal (0=Nenhum,1=Interfone,2=Botão), lixeira_piv_manual, lixeira_desl_piso
 * HALL:              hall_abertura (0|1), hall_piv_manual, hall_piv_auto, hall_desl_piso, hall_desl_teto, hall_piv_vidro
 * OUTROS:            celular_zelador (0|1), qtd_unidades
 */

const ped_all = 'ped_piv_manual+ped_piv_auto+ped_desl_piso+ped_desl_teto+ped_piv_vidro+ped_outro';
const vei_all = 'desl_p+desl_m+desl_g+basc_simples+piv_simples+piv_duplo+vei_outro';
const hall_all = 'hall_piv_manual+hall_piv_auto+hall_desl_piso+hall_desl_teto+hall_piv_vidro';

const produtos = [
  // ── REDE ─────────────────────────────────────────────────────────────────
  {
    codigo: 'RD-001',
    descricao: '*BASE (Modem Internet)',
    custo: 150.0,
    classeEquipamento: ClasseEquipamento.REDE,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'RD-002',
    descricao: 'Mikrotik 5 Portas Base',
    custo: 370.0,
    classeEquipamento: ClasseEquipamento.REDE,
    // 1 base + ROUNDUP de portas extras a cada 3 dispositivos de rede (câmeras, leitores, etc.)
    regraQtdRem:
      '1+ceil((2+leitor_tag_ped*2+antenas_tag_vei+cam_elev+cam_rem+ped_desl_piso+lixeira_desl_piso+hall_desl_piso+ped_desl_teto+hall_desl_teto+(metros_cerca>0 and metros_cerca<201?1:0)+motor_desl_g-5)/3)',
    regraQtdAut:
      '1+ceil((2+leitor_tag_ped*2+antenas_tag_vei+cam_elev+cam_aut+ped_desl_piso+lixeira_desl_piso+hall_desl_piso+ped_desl_teto+hall_desl_teto+(metros_cerca>0 and metros_cerca<201?1:0)+motor_desl_g-5)/3)',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 370.0,
  },

  // ── CONTROLE ─────────────────────────────────────────────────────────────
  {
    codigo: 'CT-001',
    descricao: 'Biometria Facial ID FACE',
    custo: 1410.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'biometria_facial+biometria_facial_vei',
    regraQtdAut: 'biometria_facial+biometria_facial_vei',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1410.0,
  },
  {
    codigo: 'CT-002',
    descricao: 'Módulo Guarita IP',
    custo: 820.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: '(leitor_tag_ped*2+biometria_digital+antenas_tag_vei==0 and controle_remoto==0)?0:1',
    regraQtdAut: '(leitor_tag_ped*2+biometria_digital+antenas_tag_vei==0 and controle_remoto==0)?0:1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 820.0,
  },
  {
    codigo: 'CT-003',
    descricao: 'Módulo Intertravamento Eclusas',
    custo: 230.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'eclusa_pedestre+eclusa_veiculo+intertrav_ped',
    regraQtdAut: 'eclusa_pedestre+eclusa_veiculo+intertrav_ped',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 230.0,
  },
  {
    codigo: 'CT-004',
    descricao: 'Receptor CTW4 (Pedestre)',
    custo: 360.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'ceil(leitor_tag_ped/4)',
    regraQtdAut: 'ceil(leitor_tag_ped/4)',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 360.0,
  },
  {
    codigo: 'CT-005',
    descricao: 'Receptor CTW4 (Hall)',
    custo: 360.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: hall_all,
    regraQtdAut: hall_all,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 360.0,
  },
  {
    codigo: 'CT-006',
    descricao: 'Receptor TX4 (Veicular)',
    custo: 350.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: `controle_remoto==1?(${vei_all}):0`,
    regraQtdAut: `controle_remoto==1?(${vei_all}):0`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 350.0,
  },
  {
    codigo: 'CT-007',
    descricao: 'Receptor Multifunção',
    custo: 712.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'ceil(antenas_tag_vei/4)+ceil(biometria_digital/4)',
    regraQtdAut: 'ceil(antenas_tag_vei/4)+ceil(biometria_digital/4)',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 712.0,
  },
  {
    codigo: 'CT-008',
    descricao: 'Leitor RFID',
    custo: 170.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'leitor_tag_ped*2',
    regraQtdAut: 'leitor_tag_ped*2',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 170.0,
  },
  {
    codigo: 'CT-009',
    descricao: 'Antena TAG Automotiva LN 6011C 12dBi',
    custo: 3818.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'antenas_tag_vei',
    regraQtdAut: 'antenas_tag_vei',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 3818.0,
  },
  {
    codigo: 'CT-010',
    descricao: 'Leitor Biometria Digital LN5P',
    custo: 1190.77,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'biometria_digital!=0?1+biometria_digital:0',
    regraQtdAut: 'biometria_digital!=0?1+biometria_digital:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1190.77,
  },
  {
    codigo: 'CT-011',
    descricao: 'Botoeira 1PT BT3000 (Portaria)',
    custo: 66.97,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    // REM: apenas se opcao_saida_ped=Botão + hall
    regraQtdRem: `(opcao_saida_ped==1?(${ped_all}):0)+(${hall_all})`,
    regraQtdAut: `(${ped_all})+(${hall_all})`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 66.97,
  },
  {
    codigo: 'CT-012',
    descricao: 'Botoeira 1PT NA/NF (Lixeira)',
    custo: 25.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'lixeira_piv_manual+lixeira_desl_piso',
    regraQtdAut: 'lixeira_piv_manual+lixeira_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 25.0,
  },
  {
    codigo: 'CT-013',
    descricao: 'Botoeira 4PT NA/NF Stilus',
    custo: 50.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: `ceil((${ped_all}+${vei_all})/4)`,
    regraQtdAut: `ceil((${ped_all}+${vei_all})/4)`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 50.0,
  },
  {
    codigo: 'CT-014',
    descricao: 'Sensor Magnético Industrial (Portaria)',
    custo: 37.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem:
      `(eclusa_pedestre==0?(${ped_all}):2*(${ped_all}))+(eclusa_veiculo==0?(${vei_all}):2*(${vei_all}))`,
    regraQtdAut:
      `(eclusa_pedestre==0?(${ped_all}):2*(${ped_all}))+(eclusa_veiculo==0?(${vei_all}):2*(${vei_all}))`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 37.0,
  },
  {
    codigo: 'CT-015',
    descricao: 'Sensor Magnético Industrial (Lixeira)',
    custo: 37.0,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'lixeira_piv_manual+2*lixeira_desl_piso',
    regraQtdAut: 'lixeira_piv_manual+2*lixeira_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 37.0,
  },
  {
    codigo: 'CT-016',
    descricao: 'Acionador de Emergência',
    custo: 115.83,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'eclusa_pedestre!=0?eclusa_pedestre:1',
    regraQtdAut: 'eclusa_pedestre!=0?eclusa_pedestre:1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 115.83,
  },
  {
    codigo: 'CT-017',
    descricao: 'Placa IPEC PortLuz c/ Relé (Portaria)',
    custo: 23.3,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem:
      `(eclusa_pedestre==0?(${ped_all}):eclusa_pedestre)+(eclusa_veiculo==0?(${vei_all}):eclusa_veiculo)`,
    regraQtdAut:
      `(eclusa_pedestre==0?(${ped_all}):eclusa_pedestre)+(eclusa_veiculo==0?(${vei_all}):eclusa_veiculo)`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 23.3,
  },
  {
    codigo: 'CT-018',
    descricao: 'Placa IPEC PortLuz c/ Relé (Lixeira)',
    custo: 23.3,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'lixeira_piv_manual+lixeira_desl_piso',
    regraQtdAut: 'lixeira_piv_manual+lixeira_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 23.3,
  },
  {
    codigo: 'CT-019',
    descricao: 'Placa IPEC PortLuz c/ Relé (Hall)',
    custo: 23.3,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: 'hall_abertura==1?hall_piv_manual+hall_piv_vidro:0',
    regraQtdAut: 'hall_abertura==1?hall_piv_manual+hall_piv_vidro:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 23.3,
  },
  {
    codigo: 'CT-020',
    descricao: 'LED Puxe/Empurre Pedestre',
    custo: 156.7,
    classeEquipamento: ClasseEquipamento.CONTROLE,
    regraQtdRem: '0',
    regraQtdAut: 'ped_piv_manual+ped_piv_vidro+hall_piv_manual+hall_piv_vidro',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 156.7,
  },

  // ── VOIP ─────────────────────────────────────────────────────────────────
  {
    codigo: 'VP-001',
    descricao: 'ATA KHOMP KAP 311',
    custo: 414.28,
    classeEquipamento: ClasseEquipamento.VOIP,
    regraQtdRem: 'integracao_interfone==1?1:0',
    regraQtdAut: '0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 414.28,
  },
  {
    codigo: 'VP-002',
    descricao: 'XPE 1001 IP Portaria (Remota/CCC)',
    custo: 1375.38,
    classeEquipamento: ClasseEquipamento.VOIP,
    regraQtdRem: 'interfone_rem',
    regraQtdAut: '0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1375.38,
  },
  {
    codigo: 'VP-003',
    descricao: 'XPE 1001 IP Lixeira (Remota)',
    custo: 1375.38,
    classeEquipamento: ClasseEquipamento.VOIP,
    regraQtdRem: 'lixeira_modal==1?1:0',
    regraQtdAut: '0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1375.38,
  },
  {
    codigo: 'VP-004',
    descricao: 'XPE 1013 IP Portaria (Autônoma)',
    custo: 1417.04,
    classeEquipamento: ClasseEquipamento.VOIP,
    regraQtdRem: '0',
    regraQtdAut: 'interfone_aut',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1417.04,
  },
  {
    codigo: 'VP-005',
    descricao: 'XPE 1013 IP Lixeira (Autônoma)',
    custo: 1417.04,
    classeEquipamento: ClasseEquipamento.VOIP,
    regraQtdRem: '0',
    regraQtdAut: 'lixeira_modal==1?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1417.04,
  },

  // ── CFTV ─────────────────────────────────────────────────────────────────
  {
    codigo: 'CF-001',
    descricao: 'DVR Tri-Híbrido Intelbras 8 Canais s/ HD',
    custo: 610.74,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: '(cam_rem+cam_elev)<=8?1:0',
    regraQtdAut: '(cam_aut+cam_elev)<=8?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1000.74,
  },
  {
    codigo: 'CF-002',
    descricao: 'DVR Tri-Híbrido Intelbras 16 Canais s/ HD',
    custo: 1008.0,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: '(cam_rem+cam_elev)>=9 and (cam_rem+cam_elev)<=18?1:0',
    regraQtdAut: '(cam_aut+cam_elev)>=9 and (cam_aut+cam_elev)<=18?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1398.0,
  },
  {
    codigo: 'CF-003',
    descricao: 'DVR Tri-Híbrido Intelbras 32 Canais s/ HD',
    custo: 2899.9,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: '(cam_rem+cam_elev)>=19 and (cam_rem+cam_elev)<=32?1:0',
    regraQtdAut: '(cam_aut+cam_elev)>=19 and (cam_aut+cam_elev)<=32?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 3396.9,
  },
  {
    codigo: 'CF-004',
    descricao: 'Câmera HDCVI Dome (Elevador)',
    custo: 140.0,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: 'cam_elev',
    regraQtdAut: 'cam_elev',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 140.0,
  },
  {
    codigo: 'CF-005',
    descricao: 'Câmera HDCVI Bullet Básico',
    custo: 160.0,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem:
      'cam_rem+cam_elev==17?cam_rem-1:(cam_rem+cam_elev==18?cam_rem-2:cam_rem)',
    regraQtdAut:
      'cam_aut+cam_elev==17?cam_aut-1:(cam_aut+cam_elev==18?cam_aut-2:cam_aut)',
    percentualRecuperavel: 80.0,
    valorRecuperavel: 128.0,
  },
  {
    codigo: 'CF-006',
    descricao: 'Câmera Bullet IP (Overflow DVR 16ch)',
    custo: 372.0,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: 'cam_rem+cam_elev==17?1:(cam_rem+cam_elev==18?2:0)',
    regraQtdAut: 'cam_aut+cam_elev==17?1:(cam_aut+cam_elev==18?2:0)',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 372.0,
  },
  {
    codigo: 'CF-007',
    descricao: 'Caixa JFL 80x80 Básico',
    custo: 4.81,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: 'cam_rem',
    regraQtdAut: 'cam_aut',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 4.81,
  },
  {
    codigo: 'CF-008',
    descricao: 'Fonte 12V 5A Colmeia (CFTV Adicional)',
    custo: 30.0,
    classeEquipamento: ClasseEquipamento.CFTV,
    regraQtdRem: 'cam_rem+cam_elev>18?2:0',
    regraQtdAut: 'cam_aut+cam_elev>18?2:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 30.0,
  },

  // ── AUTOMAÇÃO ────────────────────────────────────────────────────────────
  {
    codigo: 'AT-001',
    descricao: 'Automatizador DZ 350 PPA (Portaria Pedestre)',
    custo: 599.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_desl_piso',
    regraQtdAut: 'ped_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 599.0,
  },
  {
    codigo: 'AT-002',
    descricao: 'Automatizador DZ 350 PPA (Lixeira)',
    custo: 599.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'lixeira_desl_piso',
    regraQtdAut: 'lixeira_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 599.0,
  },
  {
    codigo: 'AT-003',
    descricao: 'Automatizador DZ 350 PPA (Hall)',
    custo: 599.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'hall_desl_piso',
    regraQtdAut: 'hall_desl_piso',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 599.0,
  },
  {
    codigo: 'AT-004',
    descricao: 'Automatizador RAC PPA (Portaria Teto)',
    custo: 1990.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_desl_teto',
    regraQtdAut: 'ped_desl_teto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1990.0,
  },
  {
    codigo: 'AT-005',
    descricao: 'Automatizador RAC PPA (Hall Teto)',
    custo: 1990.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'hall_desl_teto',
    regraQtdAut: 'hall_desl_teto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1990.0,
  },
  {
    codigo: 'AT-006',
    descricao: 'Automatizador DZ 800 PPA (Desl. P)',
    custo: 1429.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_desl_p',
    regraQtdAut: 'motor_desl_p',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1429.0,
  },
  {
    codigo: 'AT-007',
    descricao: 'Automatizador DZ 1500 PPA (Desl. M)',
    custo: 2460.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_desl_m',
    regraQtdAut: 'motor_desl_m',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 2460.0,
  },
  {
    codigo: 'AT-008',
    descricao: 'Automatizador DZ 2500 PPA (Desl. G)',
    custo: 2900.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_desl_g',
    regraQtdAut: 'motor_desl_g',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 2900.0,
  },
  {
    codigo: 'AT-009',
    descricao: 'Automatizador BC Simples PPA (Basculante)',
    custo: 3075.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_basc',
    regraQtdAut: 'motor_basc',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 3075.0,
  },
  {
    codigo: 'AT-010',
    descricao: 'Automatizador PV Simples PPA',
    custo: 1690.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_piv_simples',
    regraQtdAut: 'motor_piv_simples',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1690.0,
  },
  {
    codigo: 'AT-011',
    descricao: 'Automatizador PV Duplo PPA',
    custo: 3370.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'motor_piv_duplo',
    regraQtdAut: 'motor_piv_duplo',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 3370.0,
  },
  {
    codigo: 'AT-012',
    descricao: 'Automatizador Giro PPA (Portaria)',
    custo: 2180.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_piv_auto',
    regraQtdAut: 'ped_piv_auto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 2180.0,
  },
  {
    codigo: 'AT-013',
    descricao: 'Automatizador Giro PPA (Hall)',
    custo: 2180.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'hall_piv_auto',
    regraQtdAut: 'hall_piv_auto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 2180.0,
  },
  {
    codigo: 'AT-014',
    descricao: 'Trava Eletrônica p/ Portão BC e PV',
    custo: 130.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'basc_simples+piv_simples+2*piv_duplo',
    regraQtdAut: 'basc_simples+piv_simples+2*piv_duplo',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 146.5,
  },
  {
    codigo: 'AT-015',
    descricao: 'Cremalheira PPA',
    custo: 90.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'desl_p*2+desl_m*3+desl_g*4',
    regraQtdAut: 'desl_p*2+desl_m*3+desl_g*4',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'AT-016',
    descricao: 'Sensor IRA 115 Anti-Esmagamento (Veículo)',
    custo: 112.51,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: `2*(${vei_all})`,
    regraQtdAut: `2*(${vei_all})`,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 112.51,
  },
  {
    codigo: 'AT-017',
    descricao: 'Sensor IRA 115 Anti-Esmagamento (Pedestre)',
    custo: 112.51,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_desl_piso+ped_desl_teto+hall_desl_piso+hall_desl_teto',
    regraQtdAut: 'ped_desl_piso+ped_desl_teto+hall_desl_piso+hall_desl_teto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 112.51,
  },
  {
    codigo: 'AT-018',
    descricao: 'Eletroímã PPA 200kg c/ Sensor (Portaria)',
    custo: 180.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_piv_manual+ped_piv_auto',
    regraQtdAut: 'ped_piv_manual+ped_piv_auto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 180.0,
  },
  {
    codigo: 'AT-019',
    descricao: 'Eletroímã PPA 200kg c/ Sensor (Hall)',
    custo: 180.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'hall_piv_manual+hall_piv_auto',
    regraQtdAut: 'hall_piv_manual+hall_piv_auto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 180.0,
  },
  {
    codigo: 'AT-020',
    descricao: 'Eletroímã PPA 200kg Vidro c/ Sensor (Portaria)',
    custo: 255.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_piv_vidro',
    regraQtdAut: 'ped_piv_vidro',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 255.0,
  },
  {
    codigo: 'AT-021',
    descricao: 'Eletroímã PPA 200kg Vidro c/ Sensor (Hall)',
    custo: 255.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'hall_piv_vidro',
    regraQtdAut: 'hall_piv_vidro',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 255.0,
  },
  {
    codigo: 'AT-022',
    descricao: 'Eletroímã PPA 200kg c/ Sensor (Lixeira)',
    custo: 180.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'lixeira_piv_manual',
    regraQtdAut: 'lixeira_piv_manual',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 180.0,
  },
  {
    codigo: 'AT-023',
    descricao: 'Mola Hidráulica Dorma F2',
    custo: 170.0,
    classeEquipamento: ClasseEquipamento.AUTOMACAO,
    regraQtdRem: 'ped_piv_manual+lixeira_piv_manual+hall_piv_manual',
    regraQtdAut: 'ped_piv_manual+lixeira_piv_manual+hall_piv_manual',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 170.0,
  },

  // ── ENERGIA ──────────────────────────────────────────────────────────────
  {
    codigo: 'EN-001',
    descricao: 'No-Break Lacerda 2000VA 24V',
    custo: 850.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 850.0,
  },
  {
    codigo: 'EN-002',
    descricao: 'No-Break VoltGate 12V (Portaria)',
    custo: 1000.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: 'ped_piv_auto+ped_desl_piso+ped_desl_teto+' + vei_all,
    regraQtdAut: 'ped_piv_auto+ped_desl_piso+ped_desl_teto+' + vei_all,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1000.0,
  },
  {
    codigo: 'EN-003',
    descricao: 'No-Break VoltGate 12V (Hall e Lixeira)',
    custo: 1000.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: 'lixeira_desl_piso+hall_piv_auto+hall_desl_piso+hall_desl_teto',
    regraQtdAut: 'lixeira_desl_piso+hall_piv_auto+hall_desl_piso+hall_desl_teto',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 1000.0,
  },
  {
    codigo: 'EN-004',
    descricao: 'Bateria Estacionária 12V (Portaria)',
    custo: 320.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '2+ped_piv_auto+ped_desl_piso+ped_desl_teto+' + vei_all,
    regraQtdAut: '2+ped_piv_auto+ped_desl_piso+ped_desl_teto+' + vei_all,
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'EN-005',
    descricao: 'Bateria Estacionária 12V (Hall/Lixeira)',
    custo: 320.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: 'lixeira_desl_piso+hall_piv_auto+hall_desl_piso+hall_desl_teto',
    regraQtdAut: 'lixeira_desl_piso+hall_piv_auto+hall_desl_piso+hall_desl_teto',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'EN-006',
    descricao: 'Fonte 12V 5A Colmeia (Portaria)',
    custo: 30.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '4',
    regraQtdAut: '4',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 30.0,
  },
  {
    codigo: 'EN-007',
    descricao: 'Fonte 12V 5A Colmeia (Hall)',
    custo: 30.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: hall_all,
    regraQtdAut: hall_all,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 30.0,
  },
  {
    codigo: 'EN-008',
    descricao: 'Fonte 12V 10A Colmeia',
    custo: 45.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 45.0,
  },
  {
    codigo: 'EN-009',
    descricao: 'Anti-Surto',
    custo: 58.34,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 58.34,
  },
  {
    codigo: 'EN-010',
    descricao: 'Disjuntor 20A',
    custo: 12.66,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: '2',
    regraQtdAut: '2',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 12.66,
  },
  {
    codigo: 'EN-011',
    descricao: 'Refletor LED',
    custo: 69.0,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: 'refletores',
    regraQtdAut: 'refletores',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 69.0,
  },
  {
    codigo: 'EN-012',
    descricao: 'Fotocélula p/ Refletor',
    custo: 26.88,
    classeEquipamento: ClasseEquipamento.ENERGIA,
    regraQtdRem: 'refletores',
    regraQtdAut: 'refletores',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 26.88,
  },

  // ── INFRA ────────────────────────────────────────────────────────────────
  {
    codigo: 'IF-001',
    descricao: 'Quadro de Comando em Madeira c/ Ferragens',
    custo: 286.0,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 286.0,
  },
  {
    codigo: 'IF-002',
    descricao: 'Cooler 90x90',
    custo: 18.0,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: '2',
    regraQtdAut: '2',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 18.0,
  },
  {
    codigo: 'IF-003',
    descricao: 'Caixa Selada Steck P 17x14x9',
    custo: 20.4,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 20.4,
  },
  {
    codigo: 'IF-004',
    descricao: 'Caixa Selada Steck G (Portaria Veículos)',
    custo: 36.57,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: vei_all,
    regraQtdAut: vei_all,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 36.57,
  },
  {
    codigo: 'IF-005',
    descricao: 'Caixa Selada Steck G (Hall)',
    custo: 36.57,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: hall_all,
    regraQtdAut: hall_all,
    percentualRecuperavel: 100.0,
    valorRecuperavel: 36.57,
  },
  {
    codigo: 'IF-006',
    descricao: 'Porta Chaves em Madeira c/ Cadeado',
    custo: 48.3,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 48.3,
  },
  {
    codigo: 'IF-007',
    descricao: 'Eletroduto Rígido 1" (metros)',
    custo: 5.3,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: 'tub_rem+tub_vei',
    regraQtdAut: 'tub_aut+tub_vei',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'IF-008',
    descricao: 'Caixa 4x4 c/ Tampa Essencial',
    custo: 5.1,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: 'ceil((tub_rem+tub_vei)/12)',
    regraQtdAut: 'ceil((tub_aut+tub_vei)/12)',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'IF-009',
    descricao: 'Placa Sinalizadora Grande',
    custo: 16.5,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: `2*(${vei_all})`,
    regraQtdAut: `2*(${vei_all})`,
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'IF-010',
    descricao: 'Placa Sinalizadora Pequena',
    custo: 2.5,
    classeEquipamento: ClasseEquipamento.INFRA,
    regraQtdRem: `1+eclusa_pedestre+interfone_rem+cam_elev+lixeira_piv_manual+lixeira_desl_piso+${hall_all}+(opcao_saida_ped==1?(${ped_all}):0)`,
    regraQtdAut: `1+eclusa_pedestre+interfone_aut+cam_elev+lixeira_piv_manual+lixeira_desl_piso+${hall_all}+(${ped_all})`,
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },

  // ── ALARME ───────────────────────────────────────────────────────────────
  {
    codigo: 'AL-001',
    descricao: 'Central de Alarme 2018EG c/ Teclado',
    custo: 750.0,
    classeEquipamento: ClasseEquipamento.ALARME,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 750.0,
  },
  {
    codigo: 'AL-002',
    descricao: 'Sensor Magnético Uso Geral',
    custo: 13.0,
    classeEquipamento: ClasseEquipamento.ALARME,
    regraQtdRem: '2',
    regraQtdAut: '2',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 13.0,
  },
  {
    codigo: 'AL-003',
    descricao: 'Sirene Piezelétrica',
    custo: 16.0,
    classeEquipamento: ClasseEquipamento.ALARME,
    regraQtdRem: '1',
    regraQtdAut: '1',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 16.0,
  },

  // ── PERÍMETRO ────────────────────────────────────────────────────────────
  {
    codigo: 'PT-001',
    descricao: 'Central de Choque GCP 10000 (até 200m)',
    custo: 130.0,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'metros_cerca>0 and metros_cerca<201?1:0',
    regraQtdAut: 'metros_cerca>0 and metros_cerca<201?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 130.0,
  },
  {
    codigo: 'PT-002',
    descricao: 'Central de Choque JFL CRI (acima 200m)',
    custo: 258.57,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'metros_cerca>200?1:0',
    regraQtdAut: 'metros_cerca>200?1:0',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 258.57,
  },
  {
    codigo: 'PT-003',
    descricao: 'Sensor de Barreira PB 315 JFL Feixe Duplo',
    custo: 159.1,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'sensores_barreira',
    regraQtdAut: 'sensores_barreira',
    percentualRecuperavel: 100.0,
    valorRecuperavel: 159.1,
  },
  {
    codigo: 'PT-004',
    descricao: 'Fio de Aço Galvanizado 18 (1,24mm) — metro',
    custo: 0.22,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'metros_cerca!=0 and cerca_tipo!=0?ceil(6*metros_cerca*1.2):0',
    regraQtdAut: 'metros_cerca!=0 and cerca_tipo!=0?ceil(6*metros_cerca*1.2):0',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'PT-005',
    descricao: 'Haste Tensionadora',
    custo: 10.5,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'metros_cerca!=0 and cerca_tipo==1?ceil(metros_cerca/3.5*1/4):0',
    regraQtdAut: 'metros_cerca!=0 and cerca_tipo==1?ceil(metros_cerca/3.5*1/4):0',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'PT-006',
    descricao: 'Haste de Passagem',
    custo: 10.5,
    classeEquipamento: ClasseEquipamento.PERIMETRO,
    regraQtdRem: 'metros_cerca!=0 and cerca_tipo==1?ceil(metros_cerca/3.5*3/4):0',
    regraQtdAut: 'metros_cerca!=0 and cerca_tipo==1?ceil(metros_cerca/3.5*3/4):0',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },

  // ── DISPOSITIVOS ─────────────────────────────────────────────────────────
  {
    codigo: 'DV-001',
    descricao: 'Etiqueta TAG Blindada',
    custo: 30.0,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'tag_vei_blindada',
    regraQtdAut: 'tag_vei_blindada',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-002',
    descricao: 'Etiqueta TAG (Comum)',
    custo: 9.5,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'tag_vei_comum',
    regraQtdAut: 'tag_vei_comum',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-003',
    descricao: 'Controle Remoto 3 Teclas',
    custo: 23.99,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'controle_veiculos',
    regraQtdAut: 'controle_veiculos',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-004',
    descricao: 'Cartão RFID',
    custo: 3.95,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'ceil(tag_pedestre*0.9)',
    regraQtdAut: 'ceil(tag_pedestre*0.9)',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-005',
    descricao: 'Chaveiro RFID',
    custo: 4.85,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'floor(tag_pedestre*0.1)',
    regraQtdAut: 'floor(tag_pedestre*0.1)',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-006',
    descricao: 'Pulseira RFID',
    custo: 11.78,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'pulseira_ped',
    regraQtdAut: 'pulseira_ped',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
  {
    codigo: 'DV-007',
    descricao: 'Celular para Zelador',
    custo: 99.9,
    classeEquipamento: ClasseEquipamento.DISPOSITIVO,
    regraQtdRem: 'celular_zelador',
    regraQtdAut: 'celular_zelador',
    percentualRecuperavel: 0.0,
    valorRecuperavel: 0.0,
  },
];

const codigosAntigos = [
  'CAM-001', 'CAM-002', 'CAM-003', 'DVR-001', 'NVR-001',
  'INT-001', 'INT-002', 'CTL-001', 'CTL-002', 'LKT-001',
  'LKT-002', 'TAG-001', 'POR-001', 'POR-002', 'SRV-001',
  'NO-BREAK-001', 'RACK-001', 'SW-001', 'TOT-001', 'LED-001',
  // Códigos da versão anterior do seed
  'RD-001', 'RD-002',
  'CT-001', 'CT-002', 'CT-003', 'CT-004', 'CT-005', 'CT-006', 'CT-007',
  'DV-001', 'DV-002', 'DV-003', 'DV-004',
  'VP-001', 'VP-002', 'VP-003', 'VP-004', 'VP-005',
  'CF-001', 'CF-002', 'CF-003', 'CF-004', 'CF-005', 'CF-006',
  'AT-001', 'AT-002', 'AT-003', 'AT-004', 'AT-005', 'AT-006', 'AT-007',
  'EN-001', 'EN-002', 'EN-003', 'EN-004',
  'IF-001', 'IF-002', 'IF-003', 'IF-004',
  'AL-001', 'AL-002', 'AL-003',
  'PT-001', 'PT-002', 'PT-003', 'PT-004',
];

export async function seedProdutosExcel() {
  console.log('Importando produtos da planilha (v2 — mapeamento completo)...');

  await prisma.produto.updateMany({
    where: { codigo: { in: codigosAntigos } },
    data: { ativo: false },
  });

  for (const p of produtos) {
    await prisma.produto.upsert({
      where: { codigo: p.codigo },
      update: { ...p, ativo: true },
      create: { ...p },
    });
  }

  console.log(`${produtos.length} produtos importados/atualizados.`);
}

if (require.main === module) {
  seedProdutosExcel()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
}
